version: '2'
services:
  foreman:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
  db:
    image: postgres:9.6
    expose:
      - "5432"
